-- --------------------------------------------------------
-- hôte:                         127.0.0.1
-- version du serveur:           5.6.17 - mysql community server (gpl)
-- serveur os:                   win64
-- heidisql version:             8.3.0.4694
-- --------------------------------------------------------

-- export de la structure de la base pour msfdev
create database if not exists `msf` ;
use `msf`;


create table if not exists `t_system` (
  `db_version` varchar(10) default '02.00' comment 'version de la structure de la DB',
  `canupdate` int(1) unsigned zerofill default null,
  `updateavailable` int(1) default null
) engine=innodb default charset=utf8;

-- export de la structure de table msfdev. t_alerts
CREATE TABLE `t_alerts` (
	`idalert` INT(11) NOT NULL AUTO_INCREMENT,
	`refprocess` INT(11) NOT NULL,
	`alarmdate` DATETIME NULL DEFAULT NULL,
	`emailsent` TINYINT(4) NULL DEFAULT '0',
	`acknowledged` TINYINT(4) NULL DEFAULT '0',
	`ackbywhom` VARCHAR(50) NULL DEFAULT NULL,
	`issuecause` BLOB NULL,
	`issueaction` BLOB NULL,
	PRIMARY KEY (`idalert`),
	INDEX `refprocess` (`refprocess`)
) engine=myisam auto_increment=1 default charset=utf8;



-- export de la structure de table msfdev. t_audiofiles
create table if not exists `t_audiofiles` (
  `idaudiofile` int(11) not null auto_increment,
  `refuser` int(11) default null,
  `username` int(11) default null,
  `audiofile` varchar(255) default null,
  `filesize` int(11) default null,
  `fileurl` varchar(255) default null,
  `audioduration` int(11) default null,
  `durationspeakers` int(11) default null,
  `nbchannels` int(11) default null,
  `msffilename` varchar(255) character set utf8 collate utf8_bin default null,
  `presentondisk` int(1) not null default '1',
  `dateofadd` datetime default null,
  `typeofuse` int(1) default '0',
  primary key (`idaudiofile`),
  key `refuser` (`refuser`)
) engine=innodb default charset=utf8;


-- export de la structure de table msfdev. t_countries
create table if not exists `t_countries` (
  `ccode` varchar(2) ,
  `country` varchar(200)
) engine=innodb default charset=utf8;

-- export de données de la table msfdev.t_countries: ~246 rows (environ)
insert into `t_countries` (`ccode`, `country`) values
	('ad', 'andorra'),
	('ae', 'united arab emirates'),
	('af', 'afghanistan'),
	('ag', 'antigua and barbuda'),
	('ai', 'anguilla'),
	('al', 'albania'),
	('am', 'armenia'),
	('an', 'netherlands antilles'),
	('ao', 'angola'),
	('aq', 'antarctica'),
	('ar', 'argentina'),
	('as', 'american samoa'),
	('at', 'austria'),
	('au', 'australia'),
	('aw', 'aruba'),
	('ax', 'åland islands'),
	('az', 'azerbaijan'),
	('ba', 'bosnia and herzegovina'),
	('bb', 'barbados'),
	('bd', 'bangladesh'),
	('be', 'belgium'),
	('bf', 'burkina faso'),
	('bg', 'bulgaria'),
	('bh', 'bahrain'),
	('bi', 'burundi'),
	('bj', 'benin'),
	('bl', 'saint barthélemy'),
	('bm', 'bermuda'),
	('bn', 'brunei darussalam'),
	('bo', 'bolivia'),
	('br', 'brazil'),
	('bs', 'bahamas'),
	('bt', 'bhutan'),
	('bv', 'bouvet island'),
	('bw', 'botswana'),
	('by', 'belarus'),
	('bz', 'belize'),
	('ca', 'canada'),
	('cc', 'cocos (keeling) islands'),
	('cd', 'congo, the democratic republic of the'),
	('cf', 'central african republic'),
	('cg', 'congo'),
	('ch', 'switzerland'),
	('ci', 'côte ivoire'),
	('ck', 'cook islands'),
	('cl', 'chile'),
	('cm', 'cameroon'),
	('cn', 'china'),
	('co', 'colombia'),
	('cr', 'costa rica'),
	('cu', 'cuba'),
	('cv', 'cape verde'),
	('cx', 'christmas island'),
	('cy', 'cyprus'),
	('cz', 'czech republic'),
	('de', 'germany'),
	('dj', 'djibouti'),
	('dk', 'denmark'),
	('dm', 'dominica'),
	('do', 'dominican republic'),
	('dz', 'algeria'),
	('ec', 'ecuador'),
	('ee', 'estonia'),
	('eg', 'egypt'),
	('eh', 'western sahara'),
	('er', 'eritrea'),
	('es', 'spain'),
	('et', 'ethiopia'),
	('fi', 'finland'),
	('fj', 'fiji'),
	('fk', 'falkland islands (malvinas)'),
	('fm', 'micronesia, federated states of'),
	('fo', 'faroe islands'),
	('fr', 'france'),
	('ga', 'gabon'),
	('gb', 'united kingdom'),
	('gd', 'grenada'),
	('ge', 'georgia'),
	('gf', 'french guiana'),
	('gg', 'guernsey'),
	('gh', 'ghana'),
	('gi', 'gibraltar'),
	('gl', 'greenland'),
	('gm', 'gambia'),
	('gn', 'guinea'),
	('gp', 'guadeloupe'),
	('gq', 'equatorial guinea'),
	('gr', 'greece'),
	('gs', 'south georgia and the south sandwich islands'),
	('gt', 'guatemala'),
	('gu', 'guam'),
	('gw', 'guinea-bissau'),
	('gy', 'guyana'),
	('hk', 'hong kong'),
	('hm', 'heard island and mcdonald islands'),
	('hn', 'honduras'),
	('hr', 'croatia'),
	('ht', 'haiti'),
	('hu', 'hungary'),
	('id', 'indonesia'),
	('ie', 'ireland'),
	('il', 'israel'),
	('im', 'isle of man'),
	('in', 'india'),
	('io', 'british indian ocean territory'),
	('iq', 'iraq'),
	('ir', 'iran, islamic republic of'),
	('is', 'iceland'),
	('it', 'italy'),
	('je', 'jersey'),
	('jm', 'jamaica'),
	('jo', 'jordan'),
	('jp', 'japan'),
	('ke', 'kenya'),
	('kg', 'kyrgyzstan'),
	('kh', 'cambodia'),
	('ki', 'kiribati'),
	('km', 'comoros'),
	('kn', 'saint kitts and nevis'),
	('kp', 'korea, democratic republic of'),
	('kr', 'korea, republic of'),
	('kw', 'kuwait'),
	('ky', 'cayman islands'),
	('kz', 'kazakhstan'),
	('la', 'lao peoples democratic republic'),
	('lb', 'lebanon'),
	('lc', 'saint lucia'),
	('li', 'liechtenstein'),
	('lk', 'sri lanka'),
	('lr', 'liberia'),
	('ls', 'lesotho'),
	('lt', 'lithuania'),
	('lu', 'luxembourg'),
	('lv', 'latvia'),
	('ly', 'libyan arab jamahiriya'),
	('ma', 'morocco'),
	('mc', 'monaco'),
	('md', 'moldova, republic of'),
	('me', 'montenegro'),
	('mf', 'saint martin'),
	('mg', 'madagascar'),
	('mh', 'marshall islands'),
	('mk', 'macedonia, the former yugoslav republic of'),
	('ml', 'mali'),
	('mm', 'myanmar'),
	('mn', 'mongolia'),
	('mo', 'macao'),
	('mp', 'northern mariana islands'),
	('mq', 'martinique'),
	('mr', 'mauritania'),
	('ms', 'montserrat'),
	('mt', 'malta'),
	('mu', 'mauritius'),
	('mv', 'maldives'),
	('mw', 'malawi'),
	('mx', 'mexico'),
	('my', 'malaysia'),
	('mz', 'mozambique'),
	('na', 'namibia'),
	('nc', 'new caledonia'),
	('ne', 'niger'),
	('nf', 'norfolk island'),
	('ng', 'nigeria'),
	('ni', 'nicaragua'),
	('nl', 'netherlands'),
	('no', 'norway'),
	('np', 'nepal'),
	('nr', 'nauru'),
	('nu', 'niue'),
	('nz', 'new zealand'),
	('om', 'oman'),
	('pa', 'panama'),
	('pe', 'peru'),
	('pf', 'french polynesia'),
	('pg', 'papua new guinea'),
	('ph', 'philippines'),
	('pk', 'pakistan'),
	('pl', 'poland'),
	('pm', 'saint pierre and miquelon'),
	('pn', 'pitcairn'),
	('pr', 'puerto rico'),
	('ps', 'palestinian territory, occupied'),
	('pt', 'portugal'),
	('pw', 'palau'),
	('py', 'paraguay'),
	('qa', 'qatar'),
	('re', 'reunion'),
	('ro', 'romania'),
	('rs', 'serbia'),
	('ru', 'russian federation'),
	('rw', 'rwanda'),
	('sa', 'saudi arabia'),
	('sb', 'solomon islands'),
	('sc', 'seychelles'),
	('sd', 'sudan'),
	('se', 'sweden'),
	('sg', 'singapore'),
	('sh', 'saint helena'),
	('si', 'slovenia'),
	('sj', 'svalbard and jan mayen'),
	('sk', 'slovakia'),
	('sl', 'sierra leone'),
	('sm', 'san marino'),
	('sn', 'senegal'),
	('so', 'somalia'),
	('sr', 'suriname'),
	('st', 'sao tome and principe'),
	('sv', 'el salvador'),
	('sy', 'syrian arab republic'),
	('sz', 'swaziland'),
	('tc', 'turks and caicos islands'),
	('td', 'chad'),
	('tf', 'french southern territories'),
	('tg', 'togo'),
	('th', 'thailand'),
	('tj', 'tajikistan'),
	('tk', 'tokelau'),
	('tl', 'timor-leste'),
	('tm', 'turkmenistan'),
	('tn', 'tunisia'),
	('to', 'tonga'),
	('tr', 'turkey'),
	('tt', 'trinidad and tobago'),
	('tv', 'tuvalu'),
	('tw', 'taiwan, province of china'),
	('tz', 'tanzania, united republic of'),
	('ua', 'ukraine'),
	('ug', 'uganda'),
	('um', 'united states minor outlying islands'),
	('us', 'united states'),
	('uy', 'uruguay'),
	('uz', 'uzbekistan'),
	('va', 'holy see (vatican city state)'),
	('vc', 'saint vincent and the grenadines'),
	('ve', 'venezuela'),
	('vg', 'virgin islands, british'),
	('vi', 'virgin islands, u.s.'),
	('vn', 'viet nam'),
	('vu', 'vanuatu'),
	('wf', 'wallis and futuna'),
	('ws', 'samoa'),
	('ye', 'yemen'),
	('yt', 'mayotte'),
	('za', 'south africa'),
	('zm', 'zambia'),
	('zw', 'zimbabwe');


-- export de la structure de table msfdev. t_jobidchildren **************************         mlm voir pour virer, parie vr
create table if not exists `t_jobidchildren` (
  `nindex` int(11) not null auto_increment,
  `jobid` int(11) default null,
  `jobidchild` int(11) default null,
  primary key (`nindex`)
) engine=innodb default charset=utf8;


CREATE TABLE `t_processes` (
	`idprocess` INT(11) NOT NULL AUTO_INCREMENT,
	`clusterid` TEXT NULL,
	`jobid` INT(11) NULL DEFAULT NULL,
	`refuser` INT(11) NULL DEFAULT NULL,
	`username` VARCHAR(30) NULL DEFAULT NULL,
	`refaudiofile` INT(11) NULL DEFAULT NULL,
	`audiofile` VARCHAR(255) NULL DEFAULT NULL,
	`audioduration` VARCHAR(50) NULL DEFAULT NULL,
	`audiodurationseconds` INT(11) NULL DEFAULT NULL,
	`processname` CHAR(255) NULL DEFAULT NULL COMMENT 'texte décrivant le process transcription, alignement... ',
	`datestop` DATETIME NULL DEFAULT NULL,
	`datestart` DATETIME NULL DEFAULT NULL,
	`datesubmit` DATETIME NULL DEFAULT NULL,
	`rt` FLOAT NULL DEFAULT NULL,
	`status` CHAR(1) NULL DEFAULT NULL COMMENT 'R E Q F',
	`uuid` INT(50) NULL DEFAULT NULL COMMENT 'donne par le client',
	`errorcode` INT(11) NULL DEFAULT NULL,
	`errormessage` VARCHAR(255) NULL DEFAULT NULL,
	`hostrunner` VARCHAR(255) NULL DEFAULT NULL,
	`hostserver` VARCHAR(255) NULL DEFAULT NULL,
	`commandline` VARCHAR(1000) NULL DEFAULT NULL,
	`execnbthread` INT(11) NULL DEFAULT '1',
	`execaudiotype` CHAR(5) NULL DEFAULT NULL,
	`execlanguage` CHAR(5) NULL DEFAULT NULL,
	`execquality` INT(11) NULL DEFAULT NULL,
	`execresultinfo` CHAR(255) NULL DEFAULT NULL,
	`execcallback` CHAR(255) NULL DEFAULT NULL,
	`execcorpus` CHAR(30) NULL DEFAULT NULL,
	`progress` INT(3) NULL DEFAULT NULL,
	`sourcename` VARCHAR(255) NULL DEFAULT NULL COMMENT 'indique d où viens la commande: interface web, rest ...',
	`refstream` INT(11) NULL DEFAULT NULL,
	`datestream` DATETIME NULL DEFAULT NULL,
	`emailvoicemail` CHAR(255) NULL DEFAULT NULL,
	`durationnonspeech` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`idprocess`),
	INDEX `refuser` (`refuser`),
	INDEX `jobid` (`jobid`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


-- export de la structure de table msfdev. t_scriptexeclocation
create table if not exists `t_scriptexeclocation` (
  `indexscriptexeclocation` int(10) not null,
  `refuser` int(10) default null,
  `scriptname` char(255) not null,
  `runnername` char(255) default null,
  `queuename` char(255) default null,
  primary key (`indexscriptexeclocation`),
  key `refuser` (`refuser`)
) engine=innodb default charset=utf8;





-- export de la structure de table msfdev. t_users
CREATE TABLE `t_users` (
	`iduser` INT(11) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(30) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`info_emailaddress` CHAR(255) NOT NULL,
	`info_companyname` CHAR(128) NOT NULL,
	`info_role` CHAR(1) NULL DEFAULT NULL,
	`info_phonenumber` CHAR(128) NOT NULL,
	`info_firstname` VARCHAR(80) NULL DEFAULT NULL,
	`info_lastname` VARCHAR(80) NULL DEFAULT NULL,
	`info_creationdate` DATE NOT NULL DEFAULT '1970-01-01',
	`info_country` CHAR(2) NULL DEFAULT NULL,
	`webtemppath` CHAR(255) NOT NULL,
	`ftpdirectory` CHAR(255) NOT NULL,
	`canloginwhenmaintenance` TINYINT(4) NOT NULL DEFAULT '0',
	`actiontype` TINYINT(1) NULL DEFAULT NULL,
	`quota_maxthread` INT(11) NOT NULL DEFAULT '1',
	`quota_maxdate` DATE NOT NULL DEFAULT '1970-01-01',
	`quota_processcounter` INT(11) NULL DEFAULT NULL,
	`quota_processmaximum` INT(11) NULL DEFAULT NULL,
	`quota_scriptname` VARCHAR(80) NULL DEFAULT NULL,
	`quota_defaultmodel` VARCHAR(80) NULL DEFAULT NULL,
	`quota_processpriority` INT(11) NULL DEFAULT '0' COMMENT 'valeur entre -1024 et +1024, 0 est une priorité normale',
	`quota_hoursper24h` INT(11) NULL DEFAULT '0',
	`quota_desiredrt` INT(11) NULL DEFAULT '0',
	`quota_fastcleaning` INT(1) NULL DEFAULT '0',
	`quota_diskspace` INT(6) NULL DEFAULT '0',
	`sched_refqueue` INT(11) NULL DEFAULT '1',
	`sched_queuename` VARCHAR(45) NULL DEFAULT NULL,
	`sched_partitionname` VARCHAR(45) NULL DEFAULT NULL,
	`sched_maxprocess` INT(11) NULL DEFAULT '1',
	`sched_maxprocesssoft` INT(10) NULL DEFAULT NULL,
	`sched_priority` VARCHAR(45) NULL DEFAULT '',
	`rights_toolsallowed` CHAR(250) NOT NULL DEFAULT '',
	`rights_hourmask` INT(11) NULL DEFAULT '0',
	`rights_startcallmining` INT(1) NULL DEFAULT '0',
	`rights_multicastresults` INT(1) NULL DEFAULT '0',
	`rights_streamcontrol` INT(1) NULL DEFAULT '0',
	`rights_userspeakeridentification` INT(1) NULL DEFAULT '0',
	`rights_startspeakeridentification` INT(1) NULL DEFAULT '0',
	`rights_startmodels` INT(1) NULL DEFAULT '0',
	`rights_modelstools` INT(1) NULL DEFAULT '0',
	PRIMARY KEY (`iduser`)
) engine=innodb auto_increment=1 default charset=utf8;

insert into `t_users` (`iduser`, `username`, `password`, `info_emailaddress`, `info_companyname`, `info_role`, `quota_processpriority`, `sched_refqueue`, `info_phonenumber`, `info_firstname`, `info_lastname`, `quota_scriptname`, `quota_maxthread`,  `quota_maxdate`, `info_country`, `webtemppath`, `ftpdirectory`, `canloginwhenmaintenance`) values
	(1, 'msf', '5c7b0d85ea5525bfc40365afc1eff9f7', 'you@you.fr', 'you', 'A', 1000, 87, 'you', 'you', 'msf', 'script_vtk_transcription.php', 3, '1970-01-01', 'fr', '17a2.tmp', '/users/1/', 0);

SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
